config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
resources :dogs do
  resources :bookings, only: [:create]
end
resources :bookings, except: [:create]

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :dog

  validates :start_date, presence: true
  validates :end_date, presence: true

end

app/models/dog.rb
class Dog < ApplicationRecord
  include Geocoder


  geocoded_by :city
   after_validation :geocode, if: :will_save_change_to_city?

  belongs_to :user
  has_many :bookings
  has_many :users, through: :bookings, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }, length: { minimum: 2, maximum: 30 }
  validates :city, presence: true
  validates :description, presence: true
  validates :breed, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :dogs
  has_many :bookings

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX, message: "must be a valid email address" }
  validates :password, presence: true, length: { minimum: 6 }, format: { with: /\A(?=.*[a-zA-Z])(?=.*\d).+\z/, message: "must include at least one letter and one number" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!, only: [:show, :index]
  def index
   @bookings = Booking.where(user_id:current_user)
  end

  def show
    @booking = Booking.find(params[:id])
    @dog = @booking.dog
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.dog = Dog.find(params[:dog_id])
    @booking.user = current_user
    if @booking.save!
      redirect_to booking_path(@booking)
    else
      render 'dogs/show', status: :unprocessable_entity
    end
  end

  private

def booking_params
  params.require(:booking).permit(:start_date, :end_date)
end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  def index
    if params[:query].present?
      @dogs = Dog.where('name ILIKE ?', "%#{params[:query]}%")
    else
      @dogs = []
    end
    @all_dogs = Dog.all
    @mapbox_access_token = ENV.fetch('MAPBOX_API_KEY')
    @markers = @all_dogs.geocoded.map do |dog|
    {
      lat: dog.latitude,
      lng: dog.longitude
    }
  end
  end

  def show
    @dog = Dog.find(params[:id])
    @booking = Booking.new
  end

  def new
    @dog = Dog.new
  end

  def create
    @dog = Dog.new(dog_params)
    @dog.user = current_user
    if @dog.save
      redirect_to dog_path(@dog)
    else
      render 'dogs/new', status: :unprocessable_entity
    end
  end

  def edit
    @dog = Dog.find(params[:id])
  end
  def update
    @dog = Dog.find(params[:id])
    @dog.update(dog_params)
    if @dog.save
      redirect_to dog_path(@dog), notice: "Le profil a été édité avec succès."
    else
      render 'dogs/edit', status: :unprocessable_entity
    end
  end


  def destroy
    @dog = Dog.find(params[:id])
    @dog.destroy
    redirect_to dogs_path, status: :see_other
  end

private

def dog_params
  params.require(:dog).permit(:name, :description, :breed, :city, :start_date, :end_date, :photo)
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<!-- app/views/restaurants/new.html.erb -->

app/views/bookings/index.html.erb
<h1 class="d-flex justify-content-center my-2 pb-2"><strong>Historique de réservations</strong></h1>

 <div class="bookings-container pb-2">
  <% if @bookings.any? %>
    <% @bookings.each do |booking| %>
      <div class="card card-hover-bigger">
          <% if booking.dog.photo.present? %>
            <div class="card-category m-1 cards-booking-size"
              style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path(booking.dog.photo.key, height: 300, crop: :fill) %>')">
              <%= link_to booking.dog.name, dog_path(booking.dog), class: "card-title" %>
            </div>
          <% else %>
            <div class="card-category">
              <%= link_to dog.name, dog_path(dog), class: "card-title" %>
            </div>
          <% end %>
          <div class="card-description mb-2">
            <p class="mx-2 py-0"><strong>Race:</strong> <%= booking.dog.breed %></p>
            <p class="mx-2"><strong>Ville:</strong> <%= booking.dog.city %></p>
            <p class="mx-2"><strong>Date de la réservation:</strong><br> <%= booking.dog.start_date %></p>
          </div>
        </div>
    <% end %>
  <% else %>
    <p>Vous n'avez aucune réservation</p>
  <% end %>
</div>

app/views/bookings/show.html.erb
<h1 class="d-flex justify-content-center my-2 pb-2" >Résumé de la réservation</h1>

<div class="container">
  <div class="card-product">
    <%= cl_image_tag @dog.photo.key, height: 300, width: 400, crop: :fill %>
    <div class="card-product-infos">
      <h2 class="d-flex justify-content-center">Détails</h2>
      <p>Date de démarrage : <strong><%= @booking.start_date %></strong></p>
      <p>Date de fin : <strong><%= @booking.end_date %></strong></p>
      <p>Nom du chien : <strong><%= @booking.dog.name %></strong></p>
      <p>Race du chien : <strong><%= @booking.dog.breed %></strong></p>
      <p>Ville du chien : <strong><%= @booking.dog.city %></strong></p>
    </div>
  </div>
</div>

app/views/dogs/edit.html.erb
<div class="container m-1 pb-2 d-flex flex-column align-items-center">
<h1 class="mb-4">Editer le profil de votre chien</h1>
<%= simple_form_for @dog do |f| %>

<div class="d-flex justify-content-center">
  <%= f.input :name, input_html: { style: 'width: 300px;' } %>
  </div>
  <div class="d-flex justify-content-center">
  <%= f.input :breed, input_html: { style: 'width: 300px;' } %>
  </div>
  <div class="d-flex justify-content-center">
  <%= f.input :city, input_html: { style: 'width: 300px;' } %>
  </div>
  <div class="d-flex justify-content-center">
  <%= f.input :description, input_html: { style: 'width: 300px;' } %>
  </div>
  <%= f.input :start_date, input_html: { style: 'width: 100px;' } %>
  <%= f.input :end_date, input_html: { style: 'width: 100px;' } %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>
</div>

app/views/dogs/index.html.erb
<h1 style="text-align: center;"> Rechercher un toutou par son nom</h1>
<div class="row justify-content-center">
  <div class="col-sm-8 my-3">
    <%= form_with url: dogs_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Quel chien cherchez-vous ?" %>
      <%= submit_tag "Rechercher", name: "", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<% if params[:query].present? %>
  <div class="container-doggy-search">
    <div class="cards">
      <% if @dogs.any? %>
        <% @dogs.each do |dog| %>
          <div class="card">
            <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path dog.photo.key %>);">
              <%= link_to dog.name, dog_path(dog), class: "card-title" %>
            </div>
            <div class="card-description">
              <p><strong>Breed:</strong> <%= dog.breed %></p>
              <p><strong>City:</strong> <%= dog.city %></p>
              <p><strong>Description:</strong> <%= dog.description %></p>
            </div>
          </div>
        <% end %>
      <% else %>
        <p>Aucun chien trouvé correspondant à votre recherche.</p>
      <% end %>
    </div>
  </div>
<% end %>

<h1 class="mt-3" style="text-align: center;"> Liste des chiens disponibles</h1>

<div class="container-doggy">
  <div class="cards">
    <% if @all_dogs.any? %>
      <% @all_dogs.each do |dog| %>
        <div class="card card-hover-bigger">
          <% if dog.photo.present? %>
            <div class="card-category"
              style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path(dog.photo.key, height: 300, crop: :fill) %>')">
              <%= link_to dog.name, dog_path(dog), class: "card-title" %>
            </div>
          <% else %>
            <div class="card-category">
              <%= link_to dog.name, dog_path(dog), class: "card-title" %>
            </div>
          <% end %>
          <div class="card-description">
            <p><strong>Breed:</strong> <%= dog.breed %></p>
            <p><strong>City:</strong> <%= dog.city %></p>
          </div>
        </div>

      <% end %>
  </div>
    <% else %>
      <p>Aucun chien trouvé correspondant à votre recherche.</p>
    <% end %>
  </div>
  <div class="my-2" style="text-align: center";>
  <h1> Carte des chiens disponibles près de chez vous</h1>
  </div>
  <div class="px-5 py-2">
     <div id="map" style="width: 100%; height: 300px;"
     data-controller="map"
     data-map-markers-value="<%= @markers.to_json %>"
     data-map-api-key-value="<%= @mapbox_access_token %>">
     </div>
</div>
</div>

app/views/dogs/new.html.erb
<div class="container m-1 pb-2 d-flex flex-column align-items-center">
  <h1 class="mb-4">Enregistrez votre chien</h1>
  <%= simple_form_for @dog do |f| %>
    <div class="d-flex justify-content-center">
      <%= f.input :name, input_html: { style: 'width: 300px;' } %>
    </div>
    <div class="d-flex justify-content-center">
      <%= f.input :breed, input_html: { style: 'width: 300px;' } %>
    </div>
    <div class="d-flex justify-content-center">
      <%= f.input :city, input_html: { style: 'width: 300px;' } %>
    </div>
    <div class="d-flex justify-content-center">
      <%= f.input :description, input_html: { style: 'width: 300px;' } %>
    </div>
      <%= f.input :start_date, input_html: { style: 'width: 100px;' } %>
      <%= f.input :end_date, input_html: { style: 'width: 100px;' } %>
      <%= f.input :photo, as: :file %>
      <%= f.button :submit, class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/dogs/show.html.erb
<section class="container-dog">
<div class="card-product">
  <%= cl_image_tag @dog.photo.key, height: 300, width: 400, crop: :fill %>
  <div class="card-product-infos">
    <h2><%= @dog.name %></h2>
    <p>Descritpion du chien : <%= @dog.description %></p>
    <p>Race du chien : <%= @dog.breed %></p>
    <p>Ville : <%= @dog.city %></p>
  </div>
</div>

<div class="card-create-booking">
<h2>Create a Booking</h2>
<div class="card-create-infos">
<%= simple_form_for([@dog, @booking], url: dog_bookings_path(@dog)) do |f| %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.submit 'Create Booking' %>
<% end %>
</div>
</div>
</section>

<%= link_to "Modifier le chien", edit_dog_path(@dog), class: "btn btn-ghost" %>
<%= link_to "Supprimer le chien", dog_path(@dog), data: {turbo_method: :delete, turbo_confirm: "Etes-vous sur ?"}, class: "btn btn-ghost" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoggyNb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src='https://api.mapbox.com/mapbox-gl-js/v3.4.0/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v3.4.0/mapbox-gl.css' rel='stylesheet' />

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">


  </head>

  <body class="d-flex flex-column min-vh-100">
    <%= render "pages/navbar" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    DoggyNb copyright 2024 <i class="fas fa-heart"></i>
  </div>
</div>
  </body>
</html>

app/views/pages/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to dogs_path, class: "navbar-brand" do %>
      <%= image_tag "https://t3.ftcdn.net/jpg/02/77/80/68/360_F_277806809_9RDs2geUJlBKVX42LHHhKJzOjFdWO38N.jpg" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= image_tag "pp facebook.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log in", new_user_session_path, class: "dropdown-item" %>
              <%= link_to "Mes reservations", bookings_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.airzen.fr/wp-content/uploads/2022/10/AdobeStock_31232906-scaled-e1666964794987.jpeg);">
  <div class="container">
    <h1>Bienvenue sur <strong>DoggyNb</strong></strong>!</h1>
    <p>Trouvez un emprunteur ou un toutou proche de chez vous.</p>
    <%= link_to "Consultez les chiens disponibles", dogs_path, class: "btn btn-gradient" %>
    <%= link_to "Louer son chien", new_dog_path, class: "btn btn-gradient" %>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h1>Détails du profil</h1>